# Generated by Django 5.0.6 on 2024-07-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filechunk',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='filechunk',
            name='iv',
            field=models.CharField(default='string', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filechunk',
            name='link_lifetime',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filechunk',
            name='total_chunks',
            field=models.IntegerField(default=666),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='filechunk',
            name='index',
        ),
    ]
