# Generated by Django 5.0.6 on 2024-08-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0002_alter_filechunk_unique_together_filechunk_iv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=1000)),
                ('secret_id', models.CharField(max_length=255)),
                ('link_lifetime', models.IntegerField()),
                ('iv', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'secrets',
            },
        ),
    ]
