# Generated by Django 5.0.6 on 2024-08-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssapp', '0003_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='secret',
            field=models.CharField(max_length=10000),
        ),
    ]
